permalink: /:categories/:title.html
url: "http://roger-link.github.io"
full_name: "Roger Link"
first_name: "Roger"
last_name: "Link"
blog_title: "Blog title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "pasinduland"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Ghosteyes1"
github: "pasindud"
facebook: "mepasindu"
linkined_url: ""
